language: node_js
  - "10"

branches:
  only:
    - master

before_script:
  - yarn install

script:
  - node track/TrackChanges.js

after_success:
  - git clone "git@github.com:${TRAVIS_REPO_SLUG}" en
  - cp required-en.md required.md
  - cd en
  - git config user.name "mirucon"
  - git config user.email "i@miruc.co"
  - git add required.md
  - git commit -m "Original change detected."
  - git push --quite "https://${GH_TOKEN}@${GH_REF}" en > /dev/null 2>&1
